# Generated by Django 5.2.7 on 2025-10-18 14:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, validators=[django.core.validators.MinLengthValidator(3, 'Título muito curto.')], verbose_name='título')),
                ('done', models.BooleanField(default=False, verbose_name='concluída')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criada em')),
            ],
            options={
                'verbose_name': 'tarefa',
                'verbose_name_plural': 'tarefas',
                'ordering': ['-created_at'],
            },
        ),
    ]
